# Generated by Django 5.2 on 2025-05-03 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateField()),
                ('et_promedio', models.FloatField(blank=True, null=True)),
                ('precipitacion_promedio', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoRiego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('superficial', 'Superficial'), ('aspersion', 'Aspersión'), ('goteo', 'Goteo'), ('subterraneo', 'Subterráneo')], max_length=100)),
                ('eficiencia', models.FloatField(help_text='Eficiencia en porcentaje (0-100)')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField(help_text='Día del cronograma (1-7)')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField(default='22:00')),
                ('duracion_horas', models.FloatField(help_text='Duración en horas')),
                ('cantidad_agua', models.FloatField(help_text='Cantidad de agua en galones')),
                ('et_diario', models.FloatField(blank=True, null=True)),
                ('precipitacion', models.FloatField(blank=True, null=True)),
                ('cronograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='riego.cronograma')),
            ],
            options={
                'ordering': ['dia'],
            },
        ),
        migrations.CreateModel(
            name='TipoCultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('coef_plantula', models.FloatField(default=0.0)),
                ('coef_adulto', models.FloatField(default=0.0)),
                ('coef_anciano', models.FloatField(default=0.0)),
                ('es_predefinido', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ZonaCultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('coordenadas', models.TextField(help_text='Coordenadas en formato JSON')),
                ('area', models.FloatField(blank=True, help_text='Área en metros cuadrados', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('etapa_crecimiento', models.CharField(blank=True, choices=[('plantula', 'Plántula'), ('adulto', 'Adulto'), ('anciano', 'Anciano')], max_length=20, null=True)),
                ('tasa_flujo', models.FloatField(blank=True, help_text='Tasa de flujo en galones/hora', null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonas', to=settings.AUTH_USER_MODEL)),
                ('tipo_cultivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='riego.tipocultivo')),
                ('tipo_riego', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='riego.tiporiego')),
            ],
        ),
        migrations.AddField(
            model_name='cronograma',
            name='zona_cultivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cronogramas', to='riego.zonacultivo'),
        ),
    ]
