# Generated by Django 5.2 on 2025-05-11 08:03

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoRiego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('superficial', 'Superficial'), ('aspersion', 'Aspersión'), ('goteo', 'Goteo'), ('subterraneo', 'Subterráneo')], max_length=100)),
                ('eficiencia', models.FloatField(help_text='Eficiencia del sistema de riego (valor decimal entre 0 y 1, por ejemplo 0.75 para 75%)')),
            ],
        ),
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('etapa_crecimiento', models.CharField(choices=[('plantula', 'Plántula'), ('crecimiento', 'Crecimiento'), ('madurez', 'Madurez')], max_length=20)),
                ('tasa_flujo', models.FloatField(help_text='Tasa de flujo en galones/hora')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultivos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateField()),
                ('et_promedio', models.FloatField(blank=True, null=True)),
                ('precipitacion_promedio', models.FloatField(blank=True, null=True)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cronogramas', to='riego.cultivo')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField(help_text='Día del cronograma (1-7)')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField(default=datetime.time(22, 0))),
                ('duracion_horas', models.FloatField(help_text='Duración en horas')),
                ('cantidad_agua', models.FloatField(help_text='Cantidad de agua en galones')),
                ('et_diario', models.FloatField(blank=True, null=True)),
                ('precipitacion', models.FloatField(blank=True, null=True)),
                ('cronograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='riego.cronograma')),
            ],
            options={
                'ordering': ['dia'],
            },
        ),
        migrations.CreateModel(
            name='TipoCultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('coef_plantula', models.FloatField(default=0.0)),
                ('coef_crecimiento', models.FloatField(default=0.0)),
                ('coef_madurez', models.FloatField(default=0.0)),
                ('es_predefinido', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cultivo',
            name='tipo_cultivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='riego.tipocultivo'),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='tipo_riego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='riego.tiporiego'),
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordenadas', models.JSONField(help_text='Coordenadas GeoJSON del polígono')),
                ('area', models.FloatField(help_text='Área en metros cuadrados (calculada con Shapely)')),
                ('pais', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Ubicaciones',
            },
        ),
        migrations.AddField(
            model_name='cultivo',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultivos', to='riego.ubicacion'),
        ),
    ]
