# Generated by Django 5.2 on 2025-05-06 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipocultivo',
            old_name='coef_adulto',
            new_name='coef_crecimiento',
        ),
        migrations.RenameField(
            model_name='tipocultivo',
            old_name='coef_anciano',
            new_name='coef_madurez',
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='etapa_crecimiento',
            field=models.CharField(choices=[('plantula', 'Plántula'), ('crecimiento', 'Crecimiento'), ('madurez', 'Madurez')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tipocultivo',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
