# Generated by Django 5.2 on 2025-05-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0002_rename_coef_adulto_tipocultivo_coef_crecimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default='2023-01-01T00:00:00'),
            preserve_default=False,
        ),
    ]
